name: Deploy backend-rds

on:
  push:
    paths:
      - 'backend_rds/**'
      - '.github/workflows/backend-rds.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push backend-rds image
      run: |
        IMAGE=${{ vars.AWS_ACCAUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/backend-rds-book
        docker build -t $IMAGE ./backend_rds
        docker push $IMAGE

    - name: SSH and deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.EC2_HOST }}
        username: ${{ vars.EC2_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "🔐 Логін до ECR"
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | \
            docker login --username AWS --password-stdin ${{ vars.AWS_ACCAUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

          echo "⬇️ Завантажуємо новий образ"
          docker pull ${{ vars.AWS_ACCAUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/backend-redis-book

          echo "🔍 Перевірка порту 8000"
          sudo fuser -k 8000/tcp || true

          echo "🛠 Зупиняємо старі сервіси"
          docker-compose down || true

          echo "🧹 Очищаємо старі логи Docker"
          sudo find /var/lib/docker/containers/ -type f -name "*.log" -exec truncate -s 0 {} \;

          echo "🚀 Запускаємо сервіси"
          docker-compose up -d
